name: neat_state
packages:
  - ./
  - example/
  - example_advanced/
  - example_hydrated/
  - example_multistate/
  - example_runtask/
  - example_undoredo/

scripts:
  test:
    exec: flutter test
    description: Run tests in all packages.
  
  coverage:
    run: |
      melos exec --fail-fast -- "flutter test --coverage"
      ./scripts/merge_coverage.sh
    description: Run tests with coverage in all packages and merge results.
  # clean:
  #   exec: flutter clean
  #   packageFilters:
  #     flutter: true